# Generated by Django 4.2.8 on 2023-12-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pais",
            options={"verbose_name": "País", "verbose_name_plural": "Países"},
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pais_origen_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cliente.pais",
                verbose_name="País de origen",
            ),
        ),
    ]
