# Generated by Django 4.2.8 on 2023-12-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_alter_pais_options_alter_cliente_pais_origen_id"),
        (
            "cliente",
            "0002_alter_pais_options_cliente_emailid_cliente_telefono_and_more",
        ),
    ]

    operations = []
